spring.datasource.url=jdbc:postgresql://localhost:5432/mutual_fund_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

server.port=8080
spring.application.name=mutual-fund-advisor

scoring.scheduler.rate=300000
spring.task.scheduling.enabled=true

langchain4j.open-ai.chat-model.api-key=${GROQ_API_KEY}
langchain4j.open-ai.chat-model.base-url=https://api.groq.com/openai/v1
langchain4j.open-ai.chat-model.model-name=llama-3.1-8b-instant
  langchain4j.open-ai.chat-model.temperature=0.3
langchain4j.open-ai.chat-model.max-tokens=400